### ISSUE TITLE
Searching outside current page (index/sitemap)

### ISSUE THREAD

**Issue by yantar92** [oyvindstegard/ox-tagfilter-js#1]
Hi,
Thanks again for implementing this!

AFAIU, the code currenly works only on current html page.
It would be great to add an ability to search across the whole website if index/sitemap are available.

WDYT?

**Comment by oyvindstegard** [comment]
Hi !

First of all, this tool is not meant to be a general purpose search tool capable of searching across published Org sites. That's a different kind of project really. However, if you create a sitemap with tags, you should be able to use on in that file, to locate linked site content based on tags. Org-publish has the ability to generate a sitemap file, but I have not investigated if it is able to include tags from the documents it locates.

**Comment by yantar92** [comment]
What I had in mind is an ability to search a fixed remote page (sitemap)
in addition to the current page. Though I agree that it might be out of
scope.
